main: com.weebly.openboxtechnologies.hnrperms.Main
name: HnRPerms
version: Alpha 1.0
author: HnR Network Developer Team
description: HnRPerms Plugin
commands:
   hnrperms:
      description: Main command of the HnR Permissions System.
      usage: /<command>
